# Generated by Django 5.2.7 on 2025-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trashmodel_alter_taskmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
